language: node_js
node_js: node
before_install:
  - curl -o- -L yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
stages:
- name: test
- name: release
  if: branch = master and type = push
jobs:
  include:
  - stage: test
  - script: yarn lint
  - script: yarn test
  - stage: release
  - script: yarn build
notifications:
  email:
    on_success: never
